#Xdebug 3.x
xdebug.mode=debug,develop
xdebug.start_with_request=trigger
xdebug.trigger_value=PHPSTORM
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
xdebug.output_dir=/var/www/html/logs/xdebug
xdebug.cli_color=1